.*Assembler messages:
.*:1: Error: improper shift amount \(0\)
.*:1: Error: illegal operands .*
.*:2: Error: improper shift amount \(1\)
.*:2: Error: illegal operands .*
.*:3: Error: improper shift amount \(63\)
.*:3: Error: illegal operands .*
.*:4: Error: improper shift amount \(127\)
.*:4: Error: illegal operands .*
.*:5: Error: improper shift amount \(18446744073709551615\)
.*:5: Error: illegal operands .*
.*:6: Error: improper immediate value \(0\)
.*:6: Error: illegal operands .*
.*:7: Error: improper immediate value \(18446744073709551615\)
.*:7: Error: illegal operands .*
.*:8: Error: improper immediate value \(260\)
.*:8: Error: illegal operands .*
.*:9: Error: improper immediate value \(505\)
.*:9: Error: illegal operands .*
.*:10: Error: improper immediate value \(511\)
.*:10: Error: illegal operands .*
.*:11: Error: improper immediate value \(513\)
.*:11: Error: illegal operands .*
.*:12: Error: improper immediate value \(4081\)
.*:12: Error: illegal operands .*
.*:13: Error: improper immediate value \(4097\)
.*:13: Error: illegal operands .*
.*:14: Error: instruction srliy requires absolute expression
.*:15: Error: instruction ybndswi requires absolute expression

